// ============================================================
// FILE: lib/main.dart
// PURPOSE: Entry point of the VisaDuma Flutter app.
//
// Bootstraps:
//   • Riverpod ProviderScope (wraps entire widget tree)
//   • GoRouter (via appRouterProvider)
//   • Localisation delegates (English / Sinhala / Tamil)
//   • AppTheme (Blue & White design system)
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Auto-generated by `flutter gen-l10n` — run `flutter pub get` first.
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';

import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'shared/providers/locale_provider.dart';
import 'shared/providers/shared_providers.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise SharedPreferences before the widget tree is built.
  final prefs = await SharedPreferences.getInstance();

  // Lock to portrait mode.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Transparent status bar with dark icons over light content.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  runApp(
    // Wrap everything in ProviderScope so every widget can read Riverpod.
    ProviderScope(
      overrides: [
        // Override the lazy provider with the real SharedPreferences instance.
        sharedPreferencesProvider.overrideWithValue(prefs),
      ],
      child: const VisaDumaApp(),
    ),
  );
}

/// Root application widget.
class VisaDumaApp extends ConsumerWidget {
  const VisaDumaApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Read the GoRouter instance from Riverpod.
    final router = ref.watch(appRouterProvider);

    // Read selected locale from SharedPreferences-backed provider.
    final locale = ref.watch(localeProvider);

    return MaterialApp.router(
      // ── Router ────────────────────────────────────────────
      routerConfig: router,

      // ── Appearance ────────────────────────────────────────
      title: 'VisaDuma',
      theme: AppTheme.light,
      debugShowCheckedModeBanner: false,

      // ── Localisation ──────────────────────────────────────
      locale: locale,
      supportedLocales: const [
        Locale('en'), // English
        Locale('si'), // Sinhala
        Locale('ta'), // Tamil
      ],
      localizationsDelegates: const [
        // AppLocalizations.delegate,  // uncomment after running flutter pub get
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      localeResolutionCallback: (deviceLocale, supportedLocales) {
        if (deviceLocale != null) {
          for (final supported in supportedLocales) {
            if (supported.languageCode == deviceLocale.languageCode) {
              return supported;
            }
          }
        }
        return const Locale('en');
      },
    );
  }
}